**Implentation of any 50 numpy methods or attribute codes in jupyter notebook**

https://numpy.org/doc/stable/user/quickstart.html#simple-array-operations

In [2]:
import numpy as np

In [4]:
# 1
a= np.arange(20)

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
# 2
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
a= np.arange(20).reshape (4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
# 3 No of dimensions (count opening brackets/ ending)
a.ndim

2

In [15]:
# 4 (rows,columns)
a.shape

(4, 5)

In [16]:
# 5 (the total number of elements of the array)
a.size

20

In [18]:
# 6 (type of the elements in the array)
a.dtype

dtype('int64')

In [22]:
# shows type/class of variable
type(a)

numpy.ndarray

In [19]:
# 7 (size in bytes of each element of the array)
a.itemsize

8

In [20]:
a.dtype.itemsize

8

In [21]:
# 8 (containing the actual elements of the array)
a.data

In [29]:
# 9 (The function zeros creates an array full of zeros)

b= np.zeros ((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
f= np.zeros_like ((3, 3))
f

array([0, 0])

In [30]:
# 11 (the function ones creates an array full of ones)
c= np.ones ((3, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
e= np.ones_like ((3, 3))
e

array([1, 1])

In [31]:
# 12 (the function empty creates an array whose initial content is random and depends on the state of the memory)
d= np.empty ((3, 3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
g= np.empty_like ((3, 3))
g

array([37666352, 40434112])

In [36]:
# 13 (Return evenly spaced numbers over a specified interval.) 
# (For precision, the function linspace that receives as an argument the number of elements that we want, instead of the step)

b= np.linspace (0, 2, num=9) # provides nine numbers from 0 to 2
b

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [45]:
# 14 (One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrice)
a= np.arange (6) # one dimensional
a

array([0, 1, 2, 3, 4, 5])

In [50]:
b= np.arange(12).reshape(4,3) # two dimensional
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
c= np.arange(24).reshape(2,3,4) # Three dimensional
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [52]:
# 15 (If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners)
a= (np.arange(10000).reshape(100,100))
a

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [55]:
# 16 (he matrix product can be performed using the @ operator or the dot function or method)
A= np.array ( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )

In [56]:
A * B # element wise product

array([[2, 0],
       [0, 4]])

In [57]:
# 17 (Matrix Product)
A @ B

array([[5, 4],
       [3, 4]])

In [58]:
# (Matrix Product)
A.dot (B)

array([[5, 4],
       [3, 4]])

In [62]:
# 18 (Random numbers and Math operations)
rg = np.random.default_rng(1)
a = rg.random((2,3))
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [63]:
a.sum()

3.290252281866131

In [65]:
a.min()

0.14415961271963373

In [66]:
a.max() 

0.9504636963259353

In [68]:
# 19 (You can apply an operation along the specified axis of an array)
b = np.arange(15).reshape(5,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [70]:
b.sum (axis = 0) # sum of each column

array([30, 35, 40])

In [71]:
b.min (axis = 0)  # min of each row

array([0, 1, 2])

In [72]:
b.cumsum (axis = 0)  # Cumulative sum along each row

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26],
       [30, 35, 40]])

In [73]:
b.cumsum (axis = 1)  # Cumulative sum along each row

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30],
       [12, 25, 39]])

In [82]:
# 20 (“universal functions in numpy”(ufunc) sin, cos and exp )
B= np.arange (5)
B

array([0, 1, 2, 3, 4])

In [83]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [84]:
np.sqrt (B)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [93]:
# 21 (Test whether all array elements along a given axis evaluate to True)
np.all (B)

False

In [99]:
# 22 (Test whether any array element along a given axis evaluates to True)
np.any (B)

True

In [105]:
# 23 (Returns the indices of the maximum values along an axis)
b = np.arange(15).reshape(5,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [106]:
np.argmax(b)

14

In [108]:
# 24 (Returns the indices of the minimum values along an axis)
np.argmin(b)

0

In [114]:
# 25 (Returns the indices that would sort an array) (indirect sort)
b= np.array ([9 , 4 , 8])

np.argsort(b)

array([1, 2, 0])

In [116]:
# 26 (Compute the weighted average along the specified axis)
np.average(b)

7.0

In [119]:
# 27 (elements using fromfunction)
def f(x,y):
  return 10*x+y

In [124]:
b= np.fromfunction(f, (5,4), dtype= int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [130]:
# 28 (Slicing: Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas)
b [0:4, 1]

array([ 1, 11, 21, 31])

In [128]:
b [:, 1]

array([ 1, 11, 21, 31, 41])

In [132]:
b [1:3,]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [133]:
# 29 ( to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array)
for elements in b.flat:
  print (elements)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [134]:
# 30 (Shows pairs of array coordinates and values)
for index, x in np.ndenumerate (b):
  print (index, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 10
(1, 1) 11
(1, 2) 12
(1, 3) 13
(2, 0) 20
(2, 1) 21
(2, 2) 22
(2, 3) 23
(3, 0) 30
(3, 1) 31
(3, 2) 32
(3, 3) 33
(4, 0) 40
(4, 1) 41
(4, 2) 42
(4, 3) 43


In [139]:
# 31 (Changing the shape of an array)
a = np.floor(10*rg.random((3,4)))
a

array([[2., 2., 7., 2.],
       [4., 9., 9., 7.],
       [5., 2., 1., 9.]])

In [140]:
a.shape

(3, 4)

In [141]:
# 32 (Returns the array, flattened)
a.ravel()

array([2., 2., 7., 2., 4., 9., 9., 7., 5., 2., 1., 9.])

In [142]:
 a.reshape(6,2)  # returns the array with a modified shape

array([[2., 2.],
       [7., 2.],
       [4., 9.],
       [9., 7.],
       [5., 2.],
       [1., 9.]])

In [143]:
# 33 (Returns the array, transposed)
a.T

array([[2., 4., 5.],
       [2., 9., 2.],
       [7., 9., 1.],
       [2., 7., 9.]])

In [145]:
# 34 (Return a new array with the specified shape)
np.resize(a,(2,4))

array([[2., 2., 7., 2.],
       [4., 9., 9., 7.]])

In [148]:
# 35 (Stacking together different arrays)
a= np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [151]:
b= np.arange(4,8).reshape(2,2)
b

array([[4, 5],
       [6, 7]])

In [152]:
np.vstack((a,b)) # vertical stack

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [153]:
np.hstack((a,b)) # horizontal stack

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [167]:
# 36 (Splitting one array into several smaller ones)
a= np.arange(24).reshape(2,12)
np.floor(a)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]])

In [168]:
# Split a into 3
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [169]:
# Split a after the third and the fourth column
np.hsplit(a,(3,4))

[array([[ 0,  1,  2],
        [12, 13, 14]]), array([[ 3],
        [15]]), array([[ 4,  5,  6,  7,  8,  9, 10, 11],
        [16, 17, 18, 19, 20, 21, 22, 23]])]

In [171]:
# 37 (The identity array is a square array with ones on the main diagonal)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [174]:
# 38 (Cast an array to a specified type)
a = np.array([1, 2, 2.5])
a

array([1. , 2. , 2.5])

In [175]:
a.astype(int)

array([1, 2, 2])

In [176]:
a.astype(bool)

array([ True,  True,  True])

In [177]:
a.astype(float)

array([1. , 2. , 2.5])

In [184]:
# 39 (View inputs as arrays with given dimensions)
x = np.arange(6.0)
x
np.atleast_2d(x)

array([[0., 1., 2., 3., 4., 5.]])

In [181]:
np.atleast_3d(x)

array([[[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]]])

In [191]:
# 40 (Interpret the input as a matrix)
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [192]:
m=np.asmatrix(a)
m

matrix([[1, 2],
        [3, 4]])

In [197]:
# 41 (Join a sequence of arrays along an existing axis)
a = np.array([[2, 3], [5, 6]])
b = np.array([[7, 8]])
np.concatenate((a, b))

array([[2, 3],
       [5, 6],
       [7, 8]])

In [198]:
np.concatenate((a, b.T), axis=1)

array([[2, 3, 7],
       [5, 6, 8]])

In [199]:
np.concatenate((a, b), axis=None)

array([2, 3, 5, 6, 7, 8])

In [206]:
# 42 (Split array into multiple sub-arrays along the 3rd axis)
a = np.arange(16).reshape(2, 2, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [208]:
np.dsplit(a, 2)

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]), array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

In [213]:
# 43 (Repeat elements of an array)
a = np.array([[1,2],[3,4]])
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [214]:
a = np.array([[1,2],[3,4]])
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [217]:
# 44 (Take elements from an array along an axis)
a = [1, 2, 3, 4, 5]
indices = [0, 1, 3]
np.take(a, indices)

array([1, 2, 4])

In [218]:
# 45 (Return the indices of the elements that are non-zero)
a = np.array([[0, 3, 0], [5, 0, 0], [5, 6, 0]])
a

array([[0, 3, 0],
       [5, 0, 0],
       [5, 6, 0]])

In [219]:
np.nonzero(a)

(array([0, 1, 2, 2]), array([1, 0, 0, 1]))

In [220]:
# 46 (Return elements chosen from x or y depending on condition)
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [223]:
# 47 (Construct an array from an index array and a set of arrays to choose from)

#           0  1   2   3
choices = [ [0, 1, 2, 3], 
           [10, 11, 12, 13],
           [20, 21, 22, 23], 
           [30, 31, 32, 33]]
np.choose([2, 3, 1, 0], choices)

array([20, 31, 12,  3])

In [224]:
# 48 (Range of values (maximum - -by-maximum) along an axis)
x = np.array([[4, 9, 2, 10],
              [6, 9, 7, 12]])

In [228]:
np.ptp(x, axis=1)

array([8, 6])

In [230]:
# 49 (Find indices where elements should be inserted to maintain order)
np.searchsorted([1,2,3,4,5], 3)

2

In [233]:
# 50 (Compute the arithmetic mean along the specified axis)
a = np.array([[0, 3], [2, 5]])
np.mean(a)

2.5

# **https://www.machinelearningplus.com/python/101-numpy-exercises-python/**

In [234]:
# Q1: Import numpy as np and print the version number
import numpy as np

In [237]:
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.6/dist-packages/numpy/version.py'>


In [236]:
print(np.__version__) #shows version number

1.19.4


In [239]:
# Q2: Create a 1D array of numbers from 0 to 9
a= np.arange (10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [242]:
# Q3: Create a 3×3 numpy array of all True’s
np.ones((3,3), dtype= bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [245]:
np.full((3,3),True, dtype= bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [257]:
# Q4: Extract all odd numbers from an arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr [arr%2 == 1]

array([1, 3, 5, 7, 9])

In [255]:
# Q5: Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [261]:
# Q6: Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr%2 == 1, -1, arr)
print (arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [263]:
# Q7: Convert a 1D array to a 2D array with 2 rows
a= np.arange (10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [267]:
np.reshape (a, (2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [268]:
# Q8: Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print (a)
print (b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [275]:
np.vstack ([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [276]:
# Q9: Stack the arrays a and b horizontally
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
print (a)
print (b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [277]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [284]:
# Q10: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])

In [285]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [286]:
# Q11: Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [287]:
np.intersect1d(a,b)

array([2, 4])

In [288]:
# Q12: From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [290]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [291]:
# Q13: Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [292]:
np.where (a==b)

(array([1, 3, 5, 7]),)

In [300]:
# Q14: Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])
b= a[(a>=5)&(a<=10)]
b

array([ 6,  9, 10])

In [301]:
# Q15: Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [306]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [307]:
# Q16: Swap rows 1 and 2 in the array arr
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [311]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [313]:
# Q17: Reverse the rows of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [315]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [316]:
# Q18: Reverse the columns of a 2D array arr
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [318]:
arr [:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [322]:
# Q19: Print or show only 3 decimal places of the numpy array rand_arr
rand_arr = np.random.random((5,3))
rand_arr

array([[0.96120009, 0.37636492, 0.11011923],
       [0.2678222 , 0.94470255, 0.63385866],
       [0.77532866, 0.90219995, 0.43741732],
       [0.77151335, 0.22859681, 0.73099742],
       [0.42699828, 0.02412286, 0.55854866]])

In [325]:
np.set_printoptions(precision=3)
rand_arr

array([[0.961, 0.376, 0.11 ],
       [0.268, 0.945, 0.634],
       [0.775, 0.902, 0.437],
       [0.772, 0.229, 0.731],
       [0.427, 0.024, 0.559]])

In [326]:
# Q20: Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [334]:
np.set_printoptions(precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [335]:
# Q21: Limit the number of items printed in python numpy array a to a maximum of 6 elements
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [338]:
np.set_printoptions(threshold=6)
a= np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [339]:
# Q22: Print the full numpy array a without truncating
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [357]:
np.set_printoptions(threshold=np.inf)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [358]:
# Q23: From the array a, replace all values greater than 30 to 30 and less than 10 to 10
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.626842, 14.6401  , 21.801362, 42.39403 ,  1.231224,  6.956887,
       33.866705, 41.466785,  7.698623, 29.179573, 44.674776, 11.250904,
       10.081083,  6.310468, 11.765177, 48.952565, 40.772474,  9.42511 ,
       40.995013, 14.429614])

In [361]:
np.set_printoptions(precision=2)
np.clip(a, a_min=10, a_max=30)

array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])

In [362]:
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [367]:
# Q24: Get the positions of top 5 maximum values in a given array a
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.63, 14.64, 21.8 , 42.39,  1.23,  6.96, 33.87, 41.47,  7.7 ,
       29.18, 44.67, 11.25, 10.08,  6.31, 11.77, 48.95, 40.77,  9.43,
       41.  , 14.43])

In [378]:
print(a.argsort())

[ 4 13  5  8 17 12 11 14 19  1  2  0  9  6 16 18  7  3 10 15]


In [371]:
np.argpartition(-a, 5)[:5]

array([15, 10,  3,  7, 18])

In [379]:
# Q25: Convert array_of_arrays into a flat linear 1d array
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [388]:
arr_1d= np.concatenate (array_of_arrays)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [389]:
# Q26: Create the ranks for the given numeric array a
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)

[ 9  4 15  0 17 16 17  8  9  0]


In [392]:
print(a.argsort().argsort())
print('Array: ', a)

[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [393]:
# Q27: Create a rank array of the same shape as a given numeric array a
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [394]:
print(a.ravel().argsort().argsort().reshape(a.shape))

[[4 2 6 0 8]
 [7 9 3 5 1]]


In [395]:
# Q28: Compute the maximum for each row in the given array
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [396]:
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [397]:
# Q29: Compute the min-by-max for each row for given 2d numpy array
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [401]:
np.apply_along_axis(lambda x: np.min(x)/np.max(x),axis=1, arr=a)

array([0.44, 0.12, 0.5 , 1.  , 0.11])

In [409]:
# Q30: Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])
print (a_2d)
print (b_1d)

[[3 3 3]
 [4 4 4]
 [5 5 5]]
[1 1 1]


In [440]:
print (a_2d - b_1d[:,None])

[[2 2 2]
 [3 3 3]
 [4 4 4]]


In [452]:
# Q31: Find the index of 5th repetition of number 1 in x
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
x

array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [457]:
n=5
np.where(x == 1)[0][n-1]

8

In [459]:
[i for i, v in enumerate(x) if v == 1][n-1]

8

In [460]:
# Q32: Convert numpy's datetime64 object to datetime's datetime object
dt64 = np.datetime64('2018-02-25 22:10:10')

In [462]:
from datetime import datetime

In [463]:
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [468]:
# Q33: Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [470]:
# Q34: Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
a

array([1, 3, 7, 1, 2, 6, 0, 1])

In [471]:
diff = np.diff(np.sign(np.diff(a)))
peaks = np.where(diff == -2)[0] + 1
peaks

array([2, 5])

In [472]:
# Q35: Compute the euclidean distance between two arrays a and b
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print (a, b)

[1 2 3 4 5] [4 5 6 7 8]


In [473]:
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [474]:
# Q36: Drop all nan values from a 1D numpy array
np.array([1,2,3,np.nan,5,6,7,np.nan])

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [475]:
a[~np.isnan(a)]

array([1, 2, 3, 4, 5])

In [476]:
# Q37: Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

Array:  [0 0 3 0 2 4 2 2 2 2]


In [477]:
out = np.full(a.shape[0], True)
out

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [478]:
unique_positions = np.unique(a, return_index=True)[1]
unique_positions

array([0, 4, 2, 5])

In [479]:
out[unique_positions] = False
out

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [480]:
# Q38: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [483]:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[9.45 7.88 8.71]
 [8.15 7.91 5.1 ]
 [6.05 7.72 8.85]
 [6.25 6.43 9.26]
 [9.88 9.42 6.8 ]]


In [486]:
# Q39: Convert the function maxx that works on two scalars, to work on two arrays

def maxx(x, y):
  if x >= y:
    return x
  else:
    return y

maxx(1, 5)

5